version: '3.8'

networks:
  dev:

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    volumes:
      - ./:/var/www/
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    networks:
      - dev
    command: bash -c "wait.sh postgres:5432 -- symfony console doctrine:database:create --if-not-exists && wait.sh postgres:5432 -- symfony console doctrine:migrations:migrate --no-interaction --allow-no-migration"

  postgres:
    image: postgres:13.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - dev

  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx/
    depends_on:
      - php
    networks:
      - dev

  adminer:
    image: adminer:4
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - php
      - postgres
    networks:
      - dev
